version: '3'

services:
   nginx:
     image: huuphu310/nginx
     volumes:
       - /data/docker/nginx/conf.d:/etc/nginx/conf.d
       - /data/docker/nginx/log:/var/log/nginx
       - /data/docker/nginx/ssl:/etc/nginx/ssl
     restart: always
     ports:
       - "80:80"
       - "443:443"
