version: '3'

services:
   modsec:
     image: nginx
     volumes:
       - /data/docker/nginx/conf.d:/etc/nginx/conf.d
       - /data/docker/nginx/log:/var/log/nginx
       - /data/docker/nginx/ssl:/etc/nginx/ssl
       - /data/docker/nginx/auth:/etc/nginx/auth
       - /data/docker/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
       - /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
       - /data/docker/nginx/dhparam.pem:/etc/nginx/dhparam.pem
       - /data/docker/nginx/hosts:/etc/hosts
     restart: always
     ports:
       - "80:80"
       - "443:443"
